### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gepbird** [trumank/mint#256]
Build log:

```
error[E0658]: use of unstable library feature 'proc_macro_byte_character'
   --> /home/gep/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.89/src/wrapper.rs:886:21
    |
886 |                     proc_macro::Literal::byte_character(byte)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #115268 <https://github.com/rust-lang/rust/issues/115268> for more information
    = help: add `#![feature(proc_macro_byte_character)]` to the crate attributes to enable
    = note: this compiler was built on 2024-03-30; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'proc_macro_c_str_literals'
   --> /home/gep/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.89/src/wrapper.rs:913:21
    |
913 |                     proc_macro::Literal::c_string(string)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #119750 <https://github.com/rust-lang/rust/issues/119750> for more information
    = help: add `#![feature(proc_macro_c_str_literals)]` to the crate attributes to enable
    = note: this compiler was built on 2024-03-30; consider upgrading it if it is out of date

For more information about this error, try `rustc --explain E0658`.
error: could not compile `proc-macro2` (lib) due to 2 previous errors
```

Reproduction steps:
1. `nix develop`
2. `cargo build`

2a0e24587eefa4218e095548a75afc96ba7796f7 is the first bad commit
